#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Codenutz.XFLabs.Basics.Droid.Resource", IsApplication=true)]

namespace Codenutz.XFLabs.Basics.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_active_month_bg = global::Codenutz.XFLabs.Basics.Droid.Resource.Color.calendar_active_month_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_bg = global::Codenutz.XFLabs.Basics.Droid.Resource.Color.calendar_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_divider = global::Codenutz.XFLabs.Basics.Droid.Resource.Color.calendar_divider;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_highlighted_day_bg = global::Codenutz.XFLabs.Basics.Droid.Resource.Color.calendar_highlighted_day_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_inactive_month_bg = global::Codenutz.XFLabs.Basics.Droid.Resource.Color.calendar_inactive_month_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_selected_day_bg = global::Codenutz.XFLabs.Basics.Droid.Resource.Color.calendar_selected_day_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_selected_range_bg = global::Codenutz.XFLabs.Basics.Droid.Resource.Color.calendar_selected_range_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_active = global::Codenutz.XFLabs.Basics.Droid.Resource.Color.calendar_text_active;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_inactive = global::Codenutz.XFLabs.Basics.Droid.Resource.Color.calendar_text_inactive;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_selected = global::Codenutz.XFLabs.Basics.Droid.Resource.Color.calendar_text_selected;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_selector = global::Codenutz.XFLabs.Basics.Droid.Resource.Color.calendar_text_selector;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_unselectable = global::Codenutz.XFLabs.Basics.Droid.Resource.Color.calendar_text_unselectable;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_day_headers_paddingbottom = global::Codenutz.XFLabs.Basics.Droid.Resource.Dimension.calendar_day_headers_paddingbottom;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_month_title_bottommargin = global::Codenutz.XFLabs.Basics.Droid.Resource.Dimension.calendar_month_title_bottommargin;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_month_topmargin = global::Codenutz.XFLabs.Basics.Droid.Resource.Dimension.calendar_month_topmargin;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_text_medium = global::Codenutz.XFLabs.Basics.Droid.Resource.Dimension.calendar_text_medium;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_text_small = global::Codenutz.XFLabs.Basics.Droid.Resource.Dimension.calendar_text_small;
			global::Xamarin.Forms.Labs.Droid.Resource.Drawable.ad16 = global::Codenutz.XFLabs.Basics.Droid.Resource.Drawable.ad16;
			global::Xamarin.Forms.Labs.Droid.Resource.Drawable.calendar_bg_selector = global::Codenutz.XFLabs.Basics.Droid.Resource.Drawable.calendar_bg_selector;
			global::Xamarin.Forms.Labs.Droid.Resource.Id.calendar_grid = global::Codenutz.XFLabs.Basics.Droid.Resource.Id.calendar_grid;
			global::Xamarin.Forms.Labs.Droid.Resource.Id.calendar_view = global::Codenutz.XFLabs.Basics.Droid.Resource.Id.calendar_view;
			global::Xamarin.Forms.Labs.Droid.Resource.Id.title = global::Codenutz.XFLabs.Basics.Droid.Resource.Id.title;
			global::Xamarin.Forms.Labs.Droid.Resource.Layout.calendar_picker = global::Codenutz.XFLabs.Basics.Droid.Resource.Layout.calendar_picker;
			global::Xamarin.Forms.Labs.Droid.Resource.Layout.dialog = global::Codenutz.XFLabs.Basics.Droid.Resource.Layout.dialog;
			global::Xamarin.Forms.Labs.Droid.Resource.Layout.month = global::Codenutz.XFLabs.Basics.Droid.Resource.Layout.month;
			global::Xamarin.Forms.Labs.Droid.Resource.Layout.week = global::Codenutz.XFLabs.Basics.Droid.Resource.Layout.week;
			global::Xamarin.Forms.Labs.Droid.Resource.String.day_name_format = global::Codenutz.XFLabs.Basics.Droid.Resource.String.day_name_format;
			global::Xamarin.Forms.Labs.Droid.Resource.String.full_date_format = global::Codenutz.XFLabs.Basics.Droid.Resource.String.full_date_format;
			global::Xamarin.Forms.Labs.Droid.Resource.String.invalid_date = global::Codenutz.XFLabs.Basics.Droid.Resource.String.invalid_date;
			global::Xamarin.Forms.Labs.Droid.Resource.String.library_name = global::Codenutz.XFLabs.Basics.Droid.Resource.String.library_name;
			global::Xamarin.Forms.Labs.Droid.Resource.String.month_name_format = global::Codenutz.XFLabs.Basics.Droid.Resource.String.month_name_format;
			global::Xamarin.Forms.Labs.Droid.Resource.Style.CalendarCell = global::Codenutz.XFLabs.Basics.Droid.Resource.Style.CalendarCell;
			global::Xamarin.Forms.Labs.Droid.Resource.Style.CalendarCell_CalendarDate = global::Codenutz.XFLabs.Basics.Droid.Resource.Style.CalendarCell_CalendarDate;
			global::Xamarin.Forms.Labs.Droid.Resource.Style.CalendarCell_DayHeader = global::Codenutz.XFLabs.Basics.Droid.Resource.Style.CalendarCell_DayHeader;
			global::Xamarin.Forms.Labs.Droid.Resource.Style.CalendarTitle = global::Codenutz.XFLabs.Basics.Droid.Resource.Style.CalendarTitle;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int calendar_active_month_bg = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int calendar_bg = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int calendar_divider = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int calendar_highlighted_day_bg = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int calendar_inactive_month_bg = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int calendar_selected_day_bg = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int calendar_selected_range_bg = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int calendar_text_active = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int calendar_text_inactive = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int calendar_text_selected = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int calendar_text_selector = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int calendar_text_unselectable = 2130968586;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int calendar_day_headers_paddingbottom = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int calendar_month_title_bottommargin = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int calendar_month_topmargin = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int calendar_text_medium = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int calendar_text_small = 2131034116;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ad16 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int calendar_bg_selector = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public const int calendar_grid = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int calendar_view = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int title = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int calendar_picker = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int month = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int week = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int day_name_format = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int full_date_format = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int invalid_date = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int library_name = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int month_name_format = 2131099651;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int CalendarCell = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int CalendarCell_CalendarDate = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int CalendarCell_DayHeader = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int CalendarTitle = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
